
Tue Apr 08                                                                                                                                                                 page    1
                                                                      Default Audits Enabled on this Database

AUDIT ALTER DATABASE BY SYSTEM BY ACCESS ;
AUDIT ALTER DATABASE LINK BY SYSTEM BY ACCESS ;
AUDIT ALTER PROFILE BY SYSTEM BY ACCESS ;
AUDIT ALTER SESSION BY SYSTEM BY ACCESS ;
AUDIT ALTER SYSTEM BY SYSTEM BY ACCESS ;
AUDIT ALTER SYSTEM BY XXAPPS_RO BY ACCESS ;
AUDIT ALTER TABLESPACE BY SYSTEM BY ACCESS ;
AUDIT ALTER USER BY SYSTEM BY ACCESS ;
AUDIT AUDIT SYSTEM BY XXAPPS_RO BY ACCESS ;
AUDIT CLUSTER BY XXAPPS_RO BY ACCESS ;
AUDIT CONTEXT BY XXAPPS_RO BY ACCESS ;
AUDIT CREATE SESSION BY BRINKS BY ACCESS ;
AUDIT CREATE SESSION BY SYSTEM BY ACCESS ;
AUDIT CREATE SESSION BY XXAPPS_RO BY ACCESS ;
AUDIT DATABASE LINK BY XXAPPS_RO BY ACCESS ;
AUDIT DIMENSION BY XXAPPS_RO BY ACCESS ;
AUDIT DIRECTORY  BY ACCESS ;
AUDIT DIRECTORY BY XXAPPS_RO BY ACCESS ;
AUDIT INDEX BY XXAPPS_RO BY ACCESS ;
AUDIT MATERIALIZED VIEW BY XXAPPS_RO BY ACCESS ;
AUDIT MINING MODEL BY XXAPPS_RO BY ACCESS ;
AUDIT NOT EXISTS BY XXAPPS_RO BY ACCESS ;
AUDIT PROCEDURE BY XXAPPS_RO BY ACCESS ;
AUDIT PROFILE BY XXAPPS_RO BY ACCESS ;
AUDIT PUBLIC DATABASE LINK BY XXAPPS_RO BY ACCESS ;
AUDIT PUBLIC SYNONYM BY XXAPPS_RO BY ACCESS ;
AUDIT ROLE BY XXAPPS_RO BY ACCESS ;
AUDIT ROLLBACK SEGMENT BY XXAPPS_RO BY ACCESS ;
AUDIT SELECT TABLE BY XXAPPS_RO BY SESSION  ;
AUDIT SEQUENCE BY XXAPPS_RO BY ACCESS ;
AUDIT SYNONYM BY XXAPPS_RO BY ACCESS ;
AUDIT SYSTEM AUDIT BY XXAPPS_RO BY ACCESS ;
AUDIT SYSTEM GRANT BY XXAPPS_RO BY ACCESS ;
AUDIT TABLE BY XXAPPS_RO BY ACCESS ;
AUDIT TABLESPACE BY XXAPPS_RO BY ACCESS ;
AUDIT TRIGGER BY XXAPPS_RO BY ACCESS ;
AUDIT TYPE BY XXAPPS_RO BY ACCESS ;
AUDIT UPDATE TABLE BY XXAPPS_RO BY ACCESS ;
AUDIT USER BY XXAPPS_RO BY ACCESS ;
AUDIT VIEW BY XXAPPS_RO BY ACCESS ;
