
col STATUS format a21
col hrs format 999.99
col TIME_TAKEN_DISPLAY format a10
col INPUT_BYTES_SEC format a15
col OUTPUT_BYTES_SEC format a15
col TOTAL_OUTPUT_SIZE format a15
col TOTAL_INPUT_SIZE format a15
col END_TIME format a20
col START_TIME format a20
set lines 300
select
SESSION_KEY, INPUT_TYPE, STATUS,OUTPUT_DEVICE_TYPE,
to_char(START_TIME,'mm/dd/yy hh24:mi') start_time,
to_char(END_TIME,'mm/dd/yy hh24:mi') end_time,
ELAPSED_SECONDS,
elapsed_seconds/3600 hrs,
TIME_TAKEN_DISPLAY,
COMPRESSION_RATIO,
ROUND(INPUT_BYTES/1024/1024/1024)||'G' TOTAL_INPUT_SIZE,
INPUT_BYTES_PER_SEC_DISPLAY INPUT_BYTES_SEC,
ROUND(OUTPUT_BYTES/1024/1024/1024)||'G' TOTAL_OUTPUT_SIZE,
OUTPUT_BYTES_PER_SEC_DISPLAY OUTPUT_BYTES_SEC
from V$RMAN_BACKUP_JOB_DETAILS
order by session_key;
 
