prompt "Clearing Last Archive Timestamp for Audit Trail OS, all RAC instances..."
BEGIN
  DBMS_AUDIT_MGMT.CLEAR_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   RAC_INSTANCE_NUMBER  => 1,
   CONTAINER            =>  DBMS_AUDIT_MGMT.CONTAINER_ALL);
END;
/
BEGIN
  DBMS_AUDIT_MGMT.CLEAR_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   RAC_INSTANCE_NUMBER  => 2,
   CONTAINER            =>  DBMS_AUDIT_MGMT.CONTAINER_ALL);
END;
/
BEGIN
  DBMS_AUDIT_MGMT.CLEAR_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   RAC_INSTANCE_NUMBER  => 3,
   CONTAINER            =>  DBMS_AUDIT_MGMT.CONTAINER_ALL);
END;
/
BEGIN
  DBMS_AUDIT_MGMT.CLEAR_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   RAC_INSTANCE_NUMBER  => 4,
   CONTAINER            =>  DBMS_AUDIT_MGMT.CONTAINER_ALL);
END;
/
