create profile audit_profile limit
COMPOSITE_LIMIT                  UNLIMITED
SESSIONS_PER_USER                UNLIMITED
CPU_PER_SESSION                  UNLIMITED
CPU_PER_CALL                     UNLIMITED
LOGICAL_READS_PER_SESSION        UNLIMITED
LOGICAL_READS_PER_CALL           UNLIMITED
IDLE_TIME                        UNLIMITED
CONNECT_TIME                     UNLIMITED
PRIVATE_SGA                      UNLIMITED
FAILED_LOGIN_ATTEMPTS            7
PASSWORD_LIFE_TIME               60
PASSWORD_REUSE_TIME              730
PASSWORD_REUSE_MAX               24
PASSWORD_VERIFY_FUNCTION         VERIFY_FUNCTION_CPA
PASSWORD_LOCK_TIME               UNLIMITED
PASSWORD_GRACE_TIME              UNLIMITED
INACTIVE_ACCOUNT_TIME            DEFAULT
/
