spool &&1_out
CREATE TABLE FINANCIALS.BACKUP_&&1
(
    CREATED_BY VARCHAR2(32) NOT NULL,
    CREATION_DATE DATE NOT NULL,
    LAST_UPDATED_BY VARCHAR2(32) NOT NULL,
    LAST_UPDATED DATE NOT NULL,
    ACCOUNTING_EVENT_ID RAW(16) NOT NULL,
    BOOKING_DATE_UTC_DAY DATE NOT NULL,
    ACCOUNTING_EVENT_GROUP_ID RAW(16) NOT NULL,
    COA_DIMENSION_HASH RAW(32) NOT NULL,
    JOURNAL_DIMENSION_HASH RAW(32) NOT NULL,
    FINANCIAL_DIMENSION_HASH RAW(32) NOT NULL,
    CUSTOM_DIMENSION_HASH RAW(32) NOT NULL,
    FINANCIAL_EVENT_EXT_ID VARCHAR2(255 CHAR) NOT NULL,
-- column below to become unused
    JOURNAL_ENTRY_LINE_EXT_ID VARCHAR2(255 CHAR) NOT NULL,
    ADJUSTMENT_EXT_ID VARCHAR2(255 CHAR),
    BOOKING_DATE_UTC DATE NOT NULL,
    ACCOUNTING_DATE_UTC DATE NOT NULL,
    TRANSACTION_DATE_UTC DATE NOT NULL,
    FUNCTIONAL_CURRENCY_AMOUNT NUMBER(22,6) NOT NULL,
    FUNCTIONAL_CURRENCY_CODE VARCHAR2(3 CHAR) NOT NULL,
    FUNCTIONAL_JOURNAL_AMOUNT NUMBER(22,6) NOT NULL,
    LOCAL_CURRENCY_AMOUNT NUMBER(22,6),
    LOCAL_CURRENCY_CODE VARCHAR2(3 CHAR),
    LOCAL_JOURNAL_AMOUNT NUMBER(22,6),
    JOURNAL_SIDE VARCHAR2(1 CHAR) NOT NULL,
    QUANTITY NUMBER(19,0),
    ATTRIBUTES XMLTYPE NOT NULL
)
XMLTYPE ATTRIBUTES store as securefile clob (compress high deduplicate nocache)
PARTITION BY HASH (ACCOUNTING_EVENT_ID) PARTITIONS 16 STORE IN (BACKUP_PARTS)
TABLESPACE BACKUP_PARTS
COMPRESS FOR OLTP
PARALLEL 8
/
alter table FINANCIALS.BACKUP_&&1 set unused (JOURNAL_ENTRY_LINE_EXT_ID)
/
alter table FINANCIALS.SL_ACCOUNTING_EVENTS exchange partition &&1 with table FINANCIALS.BACKUP_&&1
/
alter table FINANCIALS.SL_ACCOUNTING_EVENTS drop partition &&1
/
spool off
exit
