DROP PROFILE C##DB_ACCT_PROFILE
/
CREATE PROFILE C##DB_ACCT_PROFILE LIMIT 
COMPOSITE_LIMIT DEFAULT 
SESSIONS_PER_USER DEFAULT 
CPU_PER_SESSION DEFAULT 
CPU_PER_CALL DEFAULT 
LOGICAL_READS_PER_SESSION DEFAULT 
LOGICAL_READS_PER_CALL DEFAULT 
IDLE_TIME UNLIMITED 
CONNECT_TIME DEFAULT 
PRIVATE_SGA DEFAULT 
FAILED_LOGIN_ATTEMPTS 7 
PASSWORD_LIFE_TIME 60 
PASSWORD_REUSE_TIME 730 
PASSWORD_REUSE_MAX 24 
PASSWORD_VERIFY_FUNCTION XXXX_PW_VERIFY_FUNCTION 
PASSWORD_LOCK_TIME UNLIMITED 
PASSWORD_GRACE_TIME 10
/

DROP PROFILE  C##APP_SVC_ACCT_PROFILE 
/
CREATE PROFILE C##APP_SVC_ACCT_PROFILE LIMIT 
COMPOSITE_LIMIT DEFAULT 
SESSIONS_PER_USER DEFAULT 
CPU_PER_SESSION DEFAULT 
CPU_PER_CALL DEFAULT 
LOGICAL_READS_PER_SESSION DEFAULT 
LOGICAL_READS_PER_CALL DEFAULT 
IDLE_TIME UNLIMITED 
CONNECT_TIME DEFAULT 
PRIVATE_SGA DEFAULT 
FAILED_LOGIN_ATTEMPTS 7 
PASSWORD_LIFE_TIME 60 
PASSWORD_REUSE_TIME 730 
PASSWORD_REUSE_MAX 24 
PASSWORD_VERIFY_FUNCTION  XXXX_PW_VERIFY_FUNCTION  
PASSWORD_LOCK_TIME UNLIMITED 
PASSWORD_GRACE_TIME 10; 

DROP PROFILE C##END_USER_ACCT_PROFILE
/
CREATE PROFILE C##END_USER_ACCT_PROFILE LIMIT 
COMPOSITE_LIMIT DEFAULT 
SESSIONS_PER_USER DEFAULT 
CPU_PER_SESSION DEFAULT 
CPU_PER_CALL DEFAULT 
LOGICAL_READS_PER_SESSION DEFAULT 
LOGICAL_READS_PER_CALL DEFAULT 
IDLE_TIME 15 
CONNECT_TIME DEFAULT 
PRIVATE_SGA DEFAULT 
FAILED_LOGIN_ATTEMPTS 7 
PASSWORD_LIFE_TIME 60 
PASSWORD_REUSE_TIME 730 
PASSWORD_REUSE_MAX 24 
PASSWORD_VERIFY_FUNCTION  XXXX_PW_VERIFY_FUNCTION  
PASSWORD_LOCK_TIME UNLIMITED 
PASSWORD_GRACE_TIME 10
/
drop profile C##DBA_ACCT_PROFILE
/
CREATE PROFILE C##DBA_ACCT_PROFILE LIMIT 
COMPOSITE_LIMIT DEFAULT 
SESSIONS_PER_USER DEFAULT 
CPU_PER_SESSION DEFAULT 
CPU_PER_CALL DEFAULT 
LOGICAL_READS_PER_SESSION DEFAULT 
LOGICAL_READS_PER_CALL DEFAULT 
IDLE_TIME 900 
CONNECT_TIME DEFAULT 
PRIVATE_SGA DEFAULT 
FAILED_LOGIN_ATTEMPTS 7 
PASSWORD_LIFE_TIME 60 
PASSWORD_REUSE_TIME 730 
PASSWORD_REUSE_MAX 24 
PASSWORD_VERIFY_FUNCTION  XXXX_PW_VERIFY_FUNCTION  
PASSWORD_LOCK_TIME UNLIMITED 
PASSWORD_GRACE_TIME 10
/
DROP PROFILE C##APP_SVC_NO_EXP_ACCT_PROFILE
/
CREATE PROFILE C##APP_SVC_NO_EXP_ACCT_PROFILE LIMIT 
COMPOSITE_LIMIT DEFAULT 
SESSIONS_PER_USER DEFAULT 
CPU_PER_SESSION DEFAULT 
CPU_PER_CALL DEFAULT 
LOGICAL_READS_PER_SESSION DEFAULT 
LOGICAL_READS_PER_CALL DEFAULT 
IDLE_TIME UNLIMITED 
CONNECT_TIME DEFAULT 
PRIVATE_SGA DEFAULT 
FAILED_LOGIN_ATTEMPTS 7 
PASSWORD_LIFE_TIME 60 
PASSWORD_REUSE_TIME 730 
PASSWORD_REUSE_MAX 24 
PASSWORD_VERIFY_FUNCTION XXXX_PW_VERIFY_FUNCTION 
PASSWORD_LOCK_TIME UNLIMITED 
PASSWORD_GRACE_TIME 10
/

