set serverout on
set feedback off

ACCEPT TDEPASS CHAR PROMPT 'TDE Password:  ' 
ACCEPT PDBNAME CHAR PROMPT 'New PDB Name:  '

BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
    BEGIN
        EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY "&&TDEPASS"';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
    EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY "&&TDEPASS"';
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE "&&PDBNAME"
        ADMIN USER "admin" IDENTIFIED BY "&&TDEPASS"
        STORAGE UNLIMITED
        TEMPFILE REUSE
        FILE_NAME_CONVERT=NONE STANDBYS=NONE';
END;
/
ALTER PLUGGABLE DATABASE "&&PDBNAME" OPEN READ WRITE
/
ALTER SESSION SET CONTAINER="&&PDBNAME"
/
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
    BEGIN
        EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY "&&TDEPASS"';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
    EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY "&&TDEPASS"';
    EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY "&&TDEPASS" WITH BACKUP';
END;
/
ALTER SESSION SET CONTAINER=CDB$ROOT
/
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY "&&TDEPASS" CONTAINER=ALL';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
    BEGIN
        EXECUTE IMMEDIATE 'SELECT * FROM GV$ENCRYPTION_WALLET';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
END;
/

prompt Make sure all PDBs and the root container
prompt have the AUTOLOGIN wallet properly opened.
prompt

