CREATE BIGFILE TABLESPACE cattbs ENCRYPTION USING 'AES256' DEFAULT STORAGE(ENCRYPT);
 CREATE USER rco IDENTIFIED BY password
  DEFAULT TABLESPACE cattbs
  QUOTA UNLIMITED ON cattbs;
GRANT recovery_catalog_owner TO rco;

