SELECT NAME,DB_UNIQUE_NAME,DATABASE_ROLE AS ROLE ,FS_FAILOVER_STATUS AS FS_STATUS,FS_FAILOVER_CURRENT_TARGET AS TARGET,FS_FAILOVER_OBSERVER_PRESENT AS OBSERVER,PROTECTION_MODE, FLASHBACK_ON FROM V$DATABASE 
/
