set line 500
set trimout on
set trimspool on
set head off
set feedback off
set echo off
spool ../../tmp/aud_stmts.sql
select     decode(ALT,'S/-','AUDIT ALTER on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT ALTER on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT ALTER on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT ALTER on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT ALTER on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT ALTER on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) altc,
           decode(AUD,'S/-','AUDIT AUDIT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT AUDIT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT AUDIT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT AUDIT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT AUDIT on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT AUDIT on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) audc,
           decode(COM,'S/-','AUDIT COMMENT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT COMMENT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT COMMENT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT COMMENT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT COMMENT on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT COMMENT on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) comc,
           decode(DEL,'S/-','AUDIT DELETE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT DELETE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT DELETE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT DELETE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT DELETE on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT DELETE on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) delc,
           decode(GRA,'S/-','AUDIT GRANT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT GRANT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT GRANT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT GRANT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT GRANT on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT GRANT on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) grac,
           decode(IND,'S/-','AUDIT INDEX on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT INDEX on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT INDEX on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT INDEX on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT INDEX on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT INDEX on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) indc,
           decode(INS,'S/-','AUDIT INSERT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT INSERT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT INSERT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT INSERT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT INSERT on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT INSERT on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) insc,
           decode(LOC,'S/-','AUDIT LOCK on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT LOCK on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT LOCK on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT LOCK on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT LOCK on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT LOCK on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) locc,
           decode(REN,'S/-','AUDIT RENAME on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT RENAME on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT RENAME on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT RENAME on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT RENAME on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT RENAME on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) renc,
           decode(SEL,'S/-','AUDIT SELECT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT SELECT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT SELECT on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT SELECT on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT SELECT on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT SELECT on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) selc,
           decode(UPD,'S/-','AUDIT UPDATE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT UPDATE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT UPDATE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT UPDATE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT UPDATE on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT UPDATE on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) updc,
           decode(EXE,'S/-','AUDIT EXECUTE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT EXECUTE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT EXECUTE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT EXECUTE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT EXECUTE on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT EXECUTE on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) exec,
           decode(CRE,'S/-','AUDIT CREATE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT CREATE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT CREATE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT CREATE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT CREATE on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT CREATE on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) crec,
           decode(REA,'S/-','AUDIT READ on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT READ on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT READ on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT READ on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT READ on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT READ on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) reac,
           decode(WRI,'S/-','AUDIT WRITE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT WRITE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT WRITE on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT WRITE on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT WRITE on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT WRITE on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) wric,
           decode(FBK,'S/-','AUDIT FLASHBACK on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by session;'||chr(10),
                      '-/S','AUDIT FLASHBACK on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by session;'||chr(10),
                      'A/-','AUDIT FLASHBACK on '||owner||'.'||object_name||' WHENEVER SUCCESSFUL by access;'||chr(10),
                      '-/A','AUDIT FLASHBACK on '||owner||'.'||object_name||' WHENEVER UNSUCCESSFUL by access;'||chr(10),
                      'S/S','AUDIT FLASHBACK on '||owner||'.'||object_name||' by session;'||chr(10),
                      'A/A','AUDIT FLASHBACK on '||owner||'.'||object_name||' by access;'||chr(10),
                      chr(10)) fbkc
from dba_obj_audit_opts
--where owner='APPLSYS'
/
spool off
set line 120
set head on
set feedback on
set echo on


