SET AUTOCOMMIT OFF
DEFINE _EDITOR = vi
SET TRIMOUT ON
SET TRIMSPOOL ON
SET VERIFY OFF
SET FEEDBACK OFF
SET TERMOUT OFF
COLUMN X NEW_VALUE Y
SELECT LOWER(USER || '@' || instance_name) X
FROM v$instance;
SET SQLPROMPT '&Y> '
column VALUE_COL_PLUS_SHOW_PARAM format a40
column NAME_COL_PLUS_SHOW_PARAM format a60
ALTER SESSION
SET NLS_DATE_FORMAT
='DD-MON-YYYY HH24:MI:SS';
ALTER SESSION
SET NLS_TIMESTAMP_FORMAT
='DD-MON-YYYY HH24:MI:SS.FF';
SELECT SYSDATE
FROM DUAL;
set serveroutput on
SET TERMOUT ON
SET FEEDBACK ON
SET LINESIZE 200
SET PAGESIZE 5000
