SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') DISCOVERY_DATE,
       S.STATUS,
       S.SERIAL#,
       S.TYPE,
       S.USERNAME,
       S.OSUSER,
       S.SERVER,
       S.MACHINE,
       S.MODULE,
       S.CLIENT_INFO,
       S.TERMINAL,
       S.PROGRAM,
       P.PROGRAM,
       TO_CHAR(S.LOGON_TIME, 'YYYY-MM-DD HH24:MI:SS'),
       LOCKWAIT,
       SI.PHYSICAL_READS,
       SI.BLOCK_GETS,
       SI.CONSISTENT_GETS,
       SI.BLOCK_CHANGES,
       SI.CONSISTENT_CHANGES,
       S.PROCESS,
       P.SPID,
       P.PID,
       SI.SID,
       S.AUDSID,
       S.SQL_ADDRESS,
       S.SQL_HASH_VALUE,
       S.ACTION,
       TO_CHAR(SYSDATE - (S.LAST_CALL_ET / (60*60*24)),'YYYY-MM-DD
HH24:MI:SS') LAST_CALL_ET_DT,
       S.LAST_CALL_ET,
       PX.QCSID,
       PX.QCSERIAL#,
       ST.SQL_TEXT
  FROM V$SESSION S,
       V$PROCESS P,
       V$SESS_IO SI,
       V$PX_SESSION PX,
       V$SQLTEXT_WITH_NEWLINES ST
 WHERE S.PADDR   = P.ADDR(+)
   and (S.SID    = PX.SID (+) AND S.SERIAL# = PX.SERIAL# (+))
   and SI.SID(+) = S.SID