
 GRANT SELECT ON SYSADM.PSSTATUS TO C##OMC_USER;
GRANT SELECT ON SYSADM.PSRELEASE TO C##OMC_USER;
GRANT SELECT ON SYSADM.PSPMAGENT TO C##OMC_USER;
GRANT SELECT ON SYSADM.PS_PTPMJMXUSER TO C##OMC_USER;
GRANT SELECT ON SYSADM.PSIBWSDLDFN TO C##OMC_USER;
GRANT SELECT ON SYSADM.PSIBSVCSETUP TO C##OMC_USER;
GRANT SELECT ON SYSADM.PS_PTSF_SRCH_ENGN TO C##OMC_USER;


