select INST_ID inst, QUEUE_NAME, QUEUE_SCHEMA, SUBSCRIBER_ADDRESS, ENQUEUED_MSGS enqm, DEQUEUED_MSGS deqm, AVG_MSG_AGE,  DEQUEUED_MSG_LATENCY deq_lat, LAST_ENQUEUE_TIME, ELAPSED_DEQUEUE_TIME, EXECUTION_COUNT exec_ct, OLDEST_MSG_ENQTM
from gv$persistent_subscribers 
where QUEUE_SCHEMA not in ('SYS','SYSTEM') 
order by inst_id, queue_schema, SUBSCRIBER_ADDRESS
/
