alter table OT_DETAIL disable constraint SYS_C002770;                                                                   
alter table AWARD disable constraint SYS_C002384;                                                                       
alter table EA disable constraint FK_EA_EMPNO;                                                                          
alter table CERT disable constraint FK_CERT_EMPNO;                                                                      
alter table VACATION disable constraint FK_VACATION_EMPNO;                                                              
alter table UTILIZATION disable constraint FK_UTILIZATION_EMPNO;                                                        
alter table USERS disable constraint FK_USERS_EMPNO;                                                                    
alter table TRAINING disable constraint FK_TRAINING_EMPNO;                                                              
alter table PAY disable constraint FK_PAY_EMPNO;                                                                        
alter table JOB disable constraint FK_JOB_EMPNO;                                                                        
alter table EMP_LOG disable constraint FK_EMPLOG_SSN;                                                                   
truncate table employee;
insert into employee select * from efierro.employee;
alter table OT_DETAIL enable constraint SYS_C002770;                                                                   
alter table AWARD enable constraint SYS_C002384;                                                                       
alter table EA enable constraint FK_EA_EMPNO;                                                                          
alter table CERT enable constraint FK_CERT_EMPNO;                                                                      
alter table VACATION enable constraint FK_VACATION_EMPNO;                                                              
alter table UTILIZATION enable constraint FK_UTILIZATION_EMPNO;                                                        
alter table USERS enable constraint FK_USERS_EMPNO;                                                                    
alter table TRAINING enable constraint FK_TRAINING_EMPNO;                                                              
alter table PAY enable constraint FK_PAY_EMPNO;                                                                        
alter table JOB enable constraint FK_JOB_EMPNO;                                                                        
alter table EMP_LOG enable constraint FK_EMPLOG_SSN;                                                                   
