set pages 1000
set line 180
prompt "Setting Last Archive Timestamp for Audit Trail OS, All RAC instances..."
BEGIN
  DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   LAST_ARCHIVE_TIME    =>  sysdate-7,
   RAC_INSTANCE_NUMBER  =>  1);
END;
/
BEGIN
  DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   LAST_ARCHIVE_TIME    =>  sysdate-7,
   RAC_INSTANCE_NUMBER  =>  2);
END;
/
BEGIN
  DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   LAST_ARCHIVE_TIME    =>  sysdate-7,
   RAC_INSTANCE_NUMBER  =>  3);
END;
/
BEGIN
  DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   LAST_ARCHIVE_TIME    =>  sysdate-7,
   RAC_INSTANCE_NUMBER  =>  4);
END;
/
select * from DBA_AUDIT_MGMT_LAST_ARCH_TS;
