set pages 1000
set line 180
prompt "Setting Last Archive Timestamp for Audit Trail OS, All RAC instances..."
BEGIN
  DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   LAST_ARCHIVE_TIME    =>  sysdate-7,
   RAC_INSTANCE_NUMBER  =>  1,
   CONTAINER            =>  DBMS_AUDIT_MGMT.CONTAINER_ALL);
END;
/
BEGIN
  DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   LAST_ARCHIVE_TIME    =>  sysdate-7,
   RAC_INSTANCE_NUMBER  =>  2,
   CONTAINER            =>  DBMS_AUDIT_MGMT.CONTAINER_ALL);
END;
/
BEGIN
  DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   LAST_ARCHIVE_TIME    =>  sysdate-7,
   RAC_INSTANCE_NUMBER  =>  3,
   CONTAINER            =>  DBMS_AUDIT_MGMT.CONTAINER_ALL);
END;
/
BEGIN
  DBMS_AUDIT_MGMT.SET_LAST_ARCHIVE_TIMESTAMP(
   AUDIT_TRAIL_TYPE     =>  DBMS_AUDIT_MGMT.AUDIT_TRAIL_OS,
   LAST_ARCHIVE_TIME    =>  sysdate-7,
   RAC_INSTANCE_NUMBER  =>  4,
   CONTAINER            =>  DBMS_AUDIT_MGMT.CONTAINER_ALL);
END;
/
select * from DBA_AUDIT_MGMT_LAST_ARCH_TS;
