set serverout on
set feedback off

ACCEPT TDEPASS CHAR PROMPT 'TDE Password:  ' 
ACCEPT PDBNAME CHAR PROMPT 'New PDB Name:  '

BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
    BEGIN
        EXECUTE IMMEDIATE 'ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY "&&TDEPASS"';
    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE "&&PDBNAME"
        ADMIN USER "admin" IDENTIFIED BY "&&TDEPASS"
        STORAGE UNLIMITED
        TEMPFILE REUSE
        FILE_NAME_CONVERT=NONE';
END;
/
ALTER PLUGGABLE DATABASE "&&PDBNAME" OPEN READ WRITE
/
ALTER SESSION SET CONTAINER="&&PDBNAME"
/

