CREATE OR REPLACE SYNONYM "C##OMC_USER"."PSSTATUS" FOR "SYSADM"."PSSTATUS";
CREATE OR REPLACE SYNONYM "C##OMC_USER"."PSRELEASE" FOR "SYSADM"."PSRELEASE";
CREATE OR REPLACE SYNONYM "C##OMC_USER"."PSPMAGENT" FOR "SYSADM"."PSPMAGENT";
CREATE OR REPLACE SYNONYM "C##OMC_USER"."PS_PTPMJMXUSER" FOR "SYSADM"."PS_PTPMJMXUSER";
CREATE OR REPLACE SYNONYM "C##OMC_USER"."PSIBWSDLDFN" FOR "SYSADM"."PSIBWSDLDFN";
CREATE OR REPLACE SYNONYM "C##OMC_USER"."PSIBSVCSETUP" FOR "SYSADM"."PSIBSVCSETUP";
CREATE OR REPLACE SYNONYM "C##OMC_USER"."PS_PTSF_SRCH_ENGN" FOR "SYSADM"."PS_PTSF_SRCH_ENGN"
