EXEC DBMS_MACADM.DELETE_COMMAND_RULE ('CONNECT', '%', '%');
EXEC DBMS_MACADM.DELETE_RULE_SET('Limit SQL*Plus Access');
EXEC DBMS_MACADM.DELETE_RULE('BLOCK_OFFSHORE_DBA');
EXEC DBMS_MACADM.DELETE_RULE('ALLOW_OTHERS');

